// movie categories
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAILED = 'LOAD_CATEGORIES_FAILED';
export const LOAD_CATEGORIES_REQUESTED = 'LOAD_CATEGORIES_REQUESTED';

// movies
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_FAILED = 'LOAD_MOVIES_FAILED';
export const LOAD_MOVIES_REQUESTED = 'LOAD_MOVIES_REQUESTED';