// movie categories
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAILED = 'LOAD_CATEGORIES_FAILED';
export const LOAD_CATEGORIES_REQUESTED = 'LOAD_CATEGORIES_REQUESTED';

// movies
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_FAILED = 'LOAD_MOVIES_FAILED';
export const LOAD_MOVIES_REQUESTED = 'LOAD_MOVIES_REQUESTED';
export const SELECT_MOVIE_CATEGORY = 'SELECT_MOVIE_CATEGORY';

// movie
export const LOAD_MOVIE_REQUESTED = 'LOAD_MOVIE_REQUESTED';
export const LOAD_MOVIE_FAILED = 'LOAD_MOVIE_FAILED';
export const LOAD_MOVIE_SUCCESS = 'LOAD_MOVIE_SUCCESS';